steps:
  - label: ":whale: Docker"
    command:
      - echo "Building image..."
      - "docker build -t asia.gcr.io/$GCLOUD_PROJECT_ID/elixir-phx-container:$BUILDKITE_COMMIT ."
      - echo "Pushing to GCR..."
      - "docker push asia.gcr.io/$GCLOUD_PROJECT_ID/elixir-phx-container:$BUILDKITE_COMMIT"

  - wait: ~
    continue_on_failure: true

  - label: ":shower: Cleanup Docker image"
    command:
      - echo "Remove local image"
      - "docker rmi asia.gcr.io/$GCLOUD_PROJECT_ID/elixir-phx-container:$BUILDKITE_COMMIT"

  - label: ":cloud: Push to Cloud Run"
    command:
      - echo "Pushing to Cloud Run"
      - "gcloud run deploy $GCLOUD_SERVICE_NAME --port 8080 --platform managed --image asia.gcr.io/$GCLOUD_PROJECT_ID/elixir-phx-container:$BUILDKITE_COMMIT --region asia-east1 --set-env-vars SECRET_KEY_BASE=$SECRET_KEY_BASE,APP_PORT=8080,COOL_TEXT=Boom --allow-unauthenticated"

  - wait: ~
    continue_on_failure: false

  - label: ":rocket: Deploy"
    command: echo "All done!"
