steps:
  - label: ":whale: First step"
    command: echo "Docker login"
    plugins:
      - docker-login#v2.0.1:
          username: moosch
          password-env: DOCKER_LOGIN_PASSWORD

  - wait

  - label: ":shipit: Deploy"
    command: echo "All done!"